### PR TITLE
WIP: Add squat example with standing ref optimization 

### PR DESCRIPTION
**Pull request by melund**
This PR adds a lower extremity squatting example which uses a standing reference recording to optimize marker positions and scale segment length. 

The example uses the Plug-in-gait protocol. 

test_plug-in-gait_squat_standigref
**Parameter optimization on single frame from standing reference recording.**

test_plug-in-gait_squat_flywheel_video
**Squating with flywheel attached to Thorax**

### To Do: 
- [x] Add option to place 'hand-of-god' on the trunk instead of Pelvis.
- [ ] Improve documentaiton

### CODE REVIEW

**Comment by melund** [comment]
@mariajnsson I plan to add the documentation for the individual examples as a Readme file in each example folder. It should not be generic in any way. Just list what is special for the particular example. 

https://github.com/AnyBody/anymocap/blob/kth_example/Examples/Plug-in-gait_Squat_StandingRefScaling/ReadMe.md

If there is any specific license you want to apply to your data files you could state it here. Otherwise, it can fall under our normal AMMR license terms, when people use it. 

You can use git to clone the repository and check out the `kth_example` branch which has the new example. Otherwise, you can always just download it as zip file: https://github.com/AnyBody/anymocap/archive/kth_example.zip

**Comment by mariajnsson** [comment]
@melund I am trying to figure out how to work with this on GitHub, guess it will be clearer as I go on :) I have been looking through the ReadMe document and I am not really sure about what I need to add, think there is not much special details to it? 

I tried to set the model up with data from one of my "real" test persons and realized that I have a problem when a marker is dropping out. Can this be solved within the model? I would like to add the arms into the model as well, even though they don't have any markers (except shoulder markers), or is this totally unnecessary? I would put them in the approximate position they were kept during the data collection. 

If we were to include the arms in the kth_example we would also have the problem of a marker drop out on RSHO, which makes it possible to include how to fix that in the example?

**Comment by melund** [comment]
> I have been looking through the ReadMe document and I am not really sure about what I need to add, think there is not much special details to it?

Don't worry about it. The Readme file will serve as documentation for other users that try your model. So  I want the special features in your example to be documented there. 

>I tried to set the model up with data from one of my "real" test persons and realized that I have a problem when a marker is dropping out. Can this be solved within the model? 

Yes. We can handle that. It is also a nice feature of the AnyMoCap framework that I would like to show of in the example. I will try to use the shoulder marker as an example of that. 

I can enable a feature that sets the marker weight to zero, when the markers drop out. It can give some problems though especially in cases where you don't have other markers to provide the missing information. But if there are other markers to provide the missing infromation, then it is a good option. Especially in cases where you can't gap-fill the missing markers. 

>I would like to add the arms into the model as well, even though they don't have any markers (except shoulder markers), or is this totally unnecessary? I would put them in the approximate position they were kept during the data collection.

It is unnecessary since you have measured ground reaction forces from force plates. We can certainly do it anyway and it will not the affect the results in any way. I also promissed to move the 'hand of god' to the trunk segment. Right. That should allow you to investigate the lower back forces without having arms in the model.

**Comment by mariajnsson** [comment]
@melund 
I found the example for marker weights in the SpecialFeatures folder and tried to insert `UseC3DWeightResiduals  = "On"` in the marker definition of the drop-out marker (RASI). I think it helped a bit but the pelvis is still "dragged" towards the origo of the GlobalRef (which is where the marker ends up when data is lost), but not as much as before.

**Comment by mariajnsson** [comment]
Is it possible to also include the extra hip markers (RILC, LILC) in the model and recreate RASI from them and the remaining pelvic markers?

**Comment by melund** [comment]
@mariajnsson  I have added arms and moved the 'hand of good' (which we will now Human-Ground residuals) to the Trunk. The last part meant a tiny refactor of the code. But that is just great. 

I also added the shoulder markers with a setting to [use the residual values from the C3D files as weights](https://github.com/AnyBody/anymocap/blob/721ffaf78697ff8fa6e5d6afbbcc5cba76dc91f4/Examples/Plug-in-gait_Squat_StandingRefScaling/MarkerProtocol.any#L386).

**Comment by melund** [comment]
Try it out as mush as you can. Then I will merge everything one of the coming days.

**Comment by melund** [comment]
Sorry. I am still having some weird issues with the model. Overloaded trunk muscles. I wil see what I can do.

**Comment by melund** [comment]
It seems to be caused by the shoulder markers dropping out. When the marker drops out it becomes zero in the data. That is interpreted as a sudden marker movement, and the low-pass filter smears that sudden movement over wider time area. So in the low-pass filtered data, the marker starts to move before the weight has been reduced to zero. 

That is a bit unfortunate. I really have to think about this one. I am afraid it is going to be hard to solve without fixing parts of the AnyBody Modeling System or implementing the filters in external python or C hooks.

**Comment by mariajnsson** [comment]
Yeah, that is the same problem as I have when I try with some other motion data that I have and the RASI marker drops out, even though I have added the weight change depending on residuals. 

Is it possible to formulate something similar to: 
```
if Residual = -1.0
exclude marker
endif
```
in the anyscript?

**Comment by melund** [comment]
@mariajnsson It is very like that it is the same issue. 

> Is it possible to formulate something similar to:
> ``` 
>    if Residual = -1.0
>    exclude marker
>    endif
> ```
No, you could not do something like that. The #if/#else logic stuff is part of the preprocessor, which runs on the source code before the model is even loaded. So you can't base the logic on something which is first known after the model is loaded. 

You can add a flag to trial specific data file `#define EXLUDE_RASIS`, and then have the exclude the marker based on that. 
```
#ifdef EXCLUDE_RASIS 
CreateMarker RASIS(..
...
...
...
#endif
```

But of course, it means that you would have to add those flags manually to the trials where you have a problem. 

I have made a change to the AnyBody Modeling System, so `AnyInputC3D` can do simple linear gap-filling on the trajectories. I will try to get it into the next beta, release for AMS 7. So maybe we can fix that way.

**Pull request merged**
